replicaCount: 1
image:
  name: bretti.net/sample-api-gateway
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  host: api.127.0.0.1.nip.io

appConfig:
  server:
    port: 8080
  openapi-route-definition-locator:
    services:
      - id: service-users
        uri: http://service-users:8080
      - id: service-orders
        uri: http://service-orders:8080
        openapi-definition-uri: /custom-path-to/openapi-definition
    update-scheduler:
      fixed-delay: 30s
      remove-routes-on-update-failures-after: 120s

