{
 "title": "Spring Cloud Gateway Dashboard",
 "description": "Spring Cloud Gateway Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(spring_cloud_gateway_routes_count, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gateway Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (httpMethod, httpStatusCode, routeUri) (rate(spring_cloud_gateway_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))*60",
     "legendFormat": "{{httpMethod}} [{{httpStatusCode}}] - {{routeUri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (httpMethod,httpStatusCode,routeUri)(rate(spring_cloud_gateway_requests_seconds_sum{instance=\"$instance\", application=\"$application\"}[$__rate_interval]))) / (sum by (httpMethod,httpStatusCode,routeUri)(rate(spring_cloud_gateway_requests_seconds_count{instance=\"$instance\", application=\"$application\"}[$__rate_interval])))",
     "legendFormat": "{{httpMethod}} [{{httpStatusCode}}] - {{routeUri}}"
    }
   ]
  },
  {
   "title": "Active Routes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "spring_cloud_gateway_routes_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "active routes"
    }
   ]
  },
  {
   "title": "Active Routes managed by OpenAPI Route Definition Locator",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openapi_route_definition_locator_routes_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{upstream_service}}"
    }
   ]
  },
  {
   "title": "Successful OpenAPI definition retrievals per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (upstream_service)(rate(openapi_route_definition_locator_openapi_definition_updates_seconds_count{instance=\"$instance\", application=\"$application\",update_result=\"success\"}[$__rate_interval])*60)",
     "legendFormat": "{{upstream_service}}"
    }
   ]
  },
  {
   "title": "Failed OpenAPI definition retrievals per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (upstream_service)(rate(openapi_route_definition_locator_openapi_definition_updates_seconds_count{instance=\"$instance\", application=\"$application\",update_result=\"failure\"}[$__rate_interval])*60)",
     "legendFormat": "{{upstream_service}}"
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ERROR logs per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[$__rate_interval])*60",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[$__rate_interval])*60",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "INFO logs per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[$__rate_interval])*60",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[$__rate_interval])*60",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[$__rate_interval])*60",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}